# Web development environment
version: "3.6"
services:

  home:
    image: vfac/envdevhome:1.2
    container_name: home
    env_file: .env
    volumes:
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
      - ./version:/var/www/html/envdev/version
      - ./profiles:/var/www/html/profiles
      - ./conf:/envdevconf
    ports:
      - '1234:80'
    links:
      - base:base
    depends_on:
      - base
    networks:
      vfac:
        ipv4_address: 172.16.238.18

  base:
    image: ${BASE_IMAGE}:${BASE_VERSION}
    container_name: base
    env_file:
      - .env
    volumes:
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
      - ./tools/phpinfo:/var/www/html/phpinfo
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./outputs/profiler:/outputs/profiler
      - ~/.gitconfig:/root/.gitconfig
      - ~/.gitconfig:/home/vfac/.gitconfig
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/vfac/.ssh
    user: "${USER_ID}:${GROUP_ID}"
    ports:
      - '22:22'

    working_dir: ${PROJECTS_PATH_DEST}
    networks:
      vfac:
        ipv4_address: ${BASE_STATIC_IP}

networks:
  vfac:
    name: vfac
    ipam:
      config:
        - subnet: 172.16.238.0/24
