# Web development environment
version: "3.6"
#services:

# Node
# node:
#   image: node:${NODE_VERSION}
#   container_name: node
#   env_file:
#     - .env
#   volumes:
#     - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
#     - ~/.gitconfig:/root/.gitconfig
#     - ~/.gitconfig:/home/vfac/.gitconfig
#     - ~/.ssh:/root/.ssh
#     - ~/.ssh:/home/vfac/.ssh
#   user: "${USER_ID}:${GROUP_ID}"
#   links:
#     - db:db
#     - cache:cache
#   working_dir: ${PROJECTS_PATH_DEST}
#   networks:
#     vfac:
#       ipv4_address: ${NODE_STATIC_IP}

volumes:
  dbdata_mariadb:
    labels:
      com.vfac.description: "VFAC EnvDev Database MariaDB volume"
      com.vfac.owner: "VFAC"
      com.vfac.url: "https://vfac.fr"
  dbdata_mysql:
    labels:
      com.vfac.description: "VFAC EnvDev Database MySQL volume"
      com.vfac.owner: "VFAC"
      com.vfac.url: "https://vfac.fr"
  dbdata_mongodb:
    labels:
      com.vfac.description: "VFAC EnvDev Database MongoDB volume"
      com.vfac.owner: "VFAC"
      com.vfac.url: "https://vfac.fr"

networks:
  vfac:
    name: vfac
    ipam:
      config:
        - subnet: 172.16.238.0/24
