# Web development environment
version: '2.1'
services:
  # To create email during development
  maildev:
    container_name: maildev
    image: djfarrelly/maildev
    ports:
        - 1025:25
        - ${MAILDEV_PORT}:80
    networks:
        - vfac

  # Web Server
  web:
    extends:
        file: services/${WEB_SERVER}.yml
        service: web
    links:
        - php:php
    networks:
        - vfac

  # PHP FPM with Composer & JS Tools
  php:
    image: vfac/envdevjs:${PHP_VERSION}
    container_name: php
    env_file:
        - .env
    volumes:
        - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
        - ./home:/var/www/html/envdev_home/
        - ./conf/php/php.ini:/usr/local/etc/php/php.ini
        - ~/.gitconfig:/root/.gitconfig
        - ~/.gitconfig:/home/vfac/.gitconfig
        - ~/.ssh:/root/.ssh
        - ~/.ssh:/home/vfac/.ssh
        - ./conf:/envdevconf
    user: "${USER_ID}:${GROUP_ID}"
    links:
        - db:db
        - maildev:maildev
        - cache:cache
        - queuer:queuer
    working_dir: ${PROJECTS_PATH_DEST}
    networks:
        - vfac

  # Cache server
  cache:
    extends:
        file: services/${CACHE_SERVER}.yml
        service: cache
    networks:
        - vfac

  # Queuer
  queuer:
    extends:
        file: services/${QUEUER_SERVER}.yml
        service: queuer
    networks:
        - vfac

  # Database
  db:
    extends:
        file: services/${DB}.yml
        service: db
    networks:
        vfac:
            aliases:
                - ${CONTAINER_DB_NAME}

  # Database admin
  dbadmin:
    extends:
        file: services/${DB}.yml
        service: dbadmin
    ports:
        - ${DBADMIN_PORT}:80
    links:
        - db
    depends_on:
        - db
    networks:
        - vfac

volumes:
  dbdata_mariadb:
    labels:
        com.vfac.description: "VFAC EnvDev Database MariaDB volume"
        com.vfac.owner: "VFAC"
        com.vfac.url: "https://vfac.fr"
  dbdata_mysql:
    labels:
        com.vfac.description: "VFAC EnvDev Database MySQL volume"
        com.vfac.owner: "VFAC"
        com.vfac.url: "https://vfac.fr"
  dbdata_mongodb:
    labels:
        com.vfac.description: "VFAC EnvDev Database MongoDB volume"
        com.vfac.owner: "VFAC"
        com.vfac.url: "https://vfac.fr"

networks:
    vfac:
        name: vfac