# Web development environment
version: "3.6"
services:

  home:
    image: vfac/envdevhome:1.0
    # build: /var/www/docker/EnvDevHome
    container_name: home
    env_file: .env
    volumes:
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
      - ./version:/var/www/html/envdev/version
    ports:
      - '1234:80'
    links:
      - base:base
    networks:
      vfac:
        ipv4_address: 172.16.238.18


networks:
  vfac:
    name: vfac
    ipam:
      config:
        - subnet: 172.16.238.0/24
