#!/bin/sh

CURRENTPATH=$(dirname "${0}");
export $(grep -v '^#' $CURRENTPATH/../.env | xargs)

docker run \
    --rm \
    -i \
    --network=host \
    -v "$PWD":"$PWD" \
    vfac/envdevjs:${PHP_VERSION} \
    git "$@"

exit $?