#!/bin/sh

# export $(grep -v '^#' .env | xargs)

# docker run \
#     --rm \
#     -i \
#     --network=host \
#     -v "${PROJECTS_PATH}":"/var/www/html/projects/":ro \
#     vfac/envdevjs:${PHP_VERSION} \
#     php "$@"

# exit $?

docker exec php php "$@"

exit $?