version: '2.1'
services:
  web:
    image: httpd:2.4-alpine
    ports:
        - ${WEB_PORT}:80
        - ${WEBSSL_PORT}:443
    container_name: web
    volumes:
        - ${PROJECTS_PATH}:/var/www/html/projects/
        - ../home:/var/www/html/envdev_home/
        - ../conf/ssl/certs:/usr/local/apache2/conf/custom
        - ../conf/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ../conf/apache/vhosts/:/etc/apache2/sites-enabled/
        - ../conf:/envdevconf