version: "3.6"
services:
  db:
    image: mariadb:${DB_VERSION}
    container_name: db
    env_file:
      - ./.env
    volumes:
      - dbdata_mariadb:/var/lib/mysql
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
    ports:
      - 3306:3306
    links:
      - base:base
      - home:home
    networks:
      vfac:
        ipv4_address: ${DB_STATIC_IP}
        aliases:
          - ${CONTAINER_DB_NAME}
  dbadmin:
    image: phpmyadmin/phpmyadmin:${DBADMIN_VERSION}
    container_name: dbadmin
    ports:
      - "${DBADMIN_PORT}:80"
    links:
      - "db:db"
    depends_on:
      - "db"
    networks:
      vfac:
        ipv4_address: ${DBADMIN_STATIC_IP}
volumes:
  dbdata_mariadb:
    labels:
      com.vfac.description: "VFAC EnvDev Database MariaDB volume"
      com.vfac.owner: "VFAC"
      com.vfac.url: "https://vfac.fr"
