version: '2.1'
services:
  db:
    image: mariadb:${DB_VERSION}
    container_name: db
    env_file:
      - ../.env
    volumes:
      - dbdata_mariadb:/var/lib/mysql
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
    ports:
      - 3306:3306
  dbadmin:
    image: phpmyadmin/phpmyadmin:${DBADMIN_VERSION}
    container_name: dbadmin
    ports:
        - "${DBADMIN_PORT}:80"

