version: "3.6"
services:
  cache:
    image: memcached:${CACHE_VERSION}
    ports:
      - ${CACHE_PORT}:6379
    container_name: cache
    links:
      - base:base
      - home:home
    networks:
      vfac:
        ipv4_address: ${CACHE_STATIC_IP}
