version: '2.1'
services:
  db:
    image: mongo:${DB_VERSION}
    container_name: db
    env_file:
      - ../.env
    volumes:
      - dbdata_mongodb:/data/db
      - ${PROJECTS_PATH}:/var/www/html/projects/
  dbadmin:
    image: mongo-express
    container_name: dbadmin

