version: '2.1'
services:
  db:
    image: mongo:${DB_VERSION}
    container_name: mongo
    env_file:
      - ../.env
    volumes:
      - dbdata_mongodb:/data/db
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
    ports:
      - "27017:27017"
  dbadmin:
    image: mongo-express:${DBADMIN_VERSION}
    container_name: dbadmin
    restart: always
    ports:
        - "${DBADMIN_PORT}:8081"

