version: '2.1'
services:
  db:
    image: mongo:${DB_VERSION}
    container_name: db
    env_file:
      - ../.env
    volumes:
      - dbdata_mongodb:/data/db
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
    ports:
      - 27017:27017
  dbadmin:
    image: mongo-express:${DBADMIN_VERSION}
    container_name: dbadmin
    environment:
      - ME_CONFIG_MONGODB_SERVER="db"

