version: '2.1'
services:
  db:
    image: mysql:${DB_VERSION}
    container_name: db
    env_file:
      - ../.env
    volumes:
      - dbdata_mysql:/var/lib/mysql
      - ${PROJECTS_PATH}:/var/www/html/projects/
  dbadmin:
    image: phpmyadmin/phpmyadmin:${DBADMIN_VERSION}
    container_name: dbadmin


