version: "3.6"
services:
  db:
    image: mysql:${DB_VERSION}
    container_name: db
    env_file:
      - ./.env
    volumes:
      - dbdata_mysql:/var/lib/mysql
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
    ports:
      - 3306:3306
    links:
      - php:php
    networks:
      vfac:
        ipv4_address: ${DB_STATIC_IP}
        aliases:
          - ${CONTAINER_DB_NAME}
  dbadmin:
    image: phpmyadmin/phpmyadmin:${DBADMIN_VERSION}
    container_name: dbadmin
    ports:
      - "${DBADMIN_PORT}:80"
    links:
      - "db:db"
    depends_on:
      - "db"
    networks:
      vfac:
        ipv4_address: ${DBADMIN_STATIC_IP}
