version: '2.1'
services:
  web:
    image: nginx:1.13-alpine
    ports:
        - ${WEB_PORT}:80
    container_name: web
    volumes:
        - ../conf/nginx/vhosts:/etc/nginx/conf.d
        - ../conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ${PROJECTS_PATH}:/var/www/html
        - ../${ENVDEV_HOME_PATH}:/var/www/html/envdev_home
