version: "3.6"
services:
  web:
    image: nginx:${WEB_VERSION}
    ports:
      - ${WEB_PORT}:80
      - ${WEBSSL_PORT}:443
    container_name: web
    volumes:
      - ./conf/nginx/vhosts:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/ssl:/etc/nginx/ssl/
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
      - ./tools/phpinfo:/var/www/html/phpinfo
    links:
      - base:base
      - home:home
    networks:
      vfac:
        ipv4_address: ${WEB_STATIC_IP}
