version: "3.6"
services:
  base:
    image: node:${NODE_VERSION}
    container_name: base
    env_file:
      - .env
    volumes:
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
      - ~/.gitconfig:/root/.gitconfig
      - ~/.gitconfig:/home/vfac/.gitconfig
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/vfac/.ssh
    user: "${USER_ID}:${GROUP_ID}"
    working_dir: ${PROJECTS_PATH_DEST}
    command: tail -f /dev/null
    networks:
      vfac:
        ipv4_address: ${NODE_STATIC_IP}