version: "3.6"
services:
  # PHP FPM with Composer & JS Tools
  base:
    image: vfac/envdevjs:${PHP_VERSION}
    container_name: base
    env_file:
      - .env
    volumes:
      - ${PROJECTS_PATH}:${PROJECTS_PATH_DEST}
      - ./tools/phpinfo:/var/www/html/phpinfo
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ~/.gitconfig:/root/.gitconfig
      - ~/.gitconfig:/home/vfac/.gitconfig
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/vfac/.ssh
    user: "${USER_ID}:${GROUP_ID}"

    working_dir: ${PROJECTS_PATH_DEST}
    networks:
      vfac:
        ipv4_address: ${PHP_STATIC_IP}
